const sidebars = {    
  frontend:[
    {
      type: 'autogenerated',
      dirName: 'frontend',
    },
  ],

  java: [    
    {
      type: 'autogenerated',
      dirName: 'java',
    },
  ],

  python: [    
    {
      type: 'autogenerated',
      dirName: 'python',
    },
  ],
   
};

export default sidebars;